apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "instagrampoststelegrambot"
  namespace: "instagrampoststelegrambot"
  labels:
    app: "instagrampoststelegrambot"
    app_type: "bot"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "instagrampoststelegrambot"
      app_type: "bot"
  template:
    metadata:
      labels:
        app: "instagrampoststelegrambot"
        app_type: "bot"
    spec:
      containers:
      - name: "instagrampoststelegrambot-1"
        image: LATEST_IMAGE_TAG
        env:
        - name: "BOT_API_TOKEN"
          valueFrom:
            configMapKeyRef:
              key: "BOT_API_TOKEN"
              name: "instagrampoststelegrambot-config-1rw8"
